source 'https://rubygems.org'
gem 'rails'
gem 'sqlite3'
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end
gem 'haml-rails'
gem 'compass-rails'
gem 'jquery-rails'
gem 'nokogiri'
gem 'builder'
gem 'json'
gem 'devise'